[google]
client_id = "1038239451526-hkupdin2re5gr0f7k2cfbem44a172ha5.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://insight.delaphonegh.net"

[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 1024
